### ISSUE TITLE
Evolution stalls with these intial conditions and parameters

### ISSUE THREAD

**Issue by kpenev** [kpenev/poet#16]
Initial Conditions
=============
PRIMARY MASS =  1.0208328796081652
SECONDARY MASS =  0.7022364956055686
P0 = 4.881682292837919,

Parameters:
==========
Pdisk = 1.4311397660850234
convective phase lag =  5.7726669277786535e-06
disk_dissipation_age = 5e-3,
wind_saturation_frequency = 2.54,
diff_rot_coupling_timescale = 5e-3,
wind_strength = 0.17,
inclination=scipy.pi/2

Present day values:
================
P0 = 4.881682292837919
Pdisk = 1.4311397660850234

**Comment by kpenev** [comment]
This is not a fully specified set of parameters. The following are not specified:
  * [Fe/H]
  * Is the phase lag only for the primary star or for the secondary as well
  * The initial angular momentum of the secondary core and envelope

**Comment by kpenev** [comment]
Actually with debugging on, an assertion is violated, when running an evolution complimenting the specified parameters with:
  * [Fe/H] = 0
  * zero phase lag for the secondary
  * Secondary envelope angular momentum of: 0.79097531984229608
  * Secondary core angular momentum of: 7.6031508107941889e-02

**Comment by kpenev** [comment]
Evolution seems to work now, as long as the dissipation for non-dissipative zones is not set to zero (i.e. leave the zones in the default state where they are assumed non-dissipative).

**Comment by ruskin23** [comment]
+    age = 2.6361887829110797
+    primary_mass = 0.9735205066895405
+    secondary_mass = 0.7522396868226867
+    initial_disk_period = 1.4064967495370835
+    initial_orbital_period = 5.2663825

**Comment by ruskin23** [comment]
Feh = -0.317892129759198

**Comment by kpenev** [comment]
For the following parameters the initial condition solver is stuck between 2 values:

tdisk = 5e-3
age = 4.60
primary_mass = 1.0232841210154926
secondary_mass =0.7932453911599053
initial_disk_period =1.4064967495370835
orbital_period = 5.2663825

metallicity = -0.06
logQ = 7.25

**Comment by kpenev** [comment]
These evolutions stalled because a spin-orbit synchronous rotation was achieved with precisely zero above lock fraction required to maintain the lock. This was not correctly handled in the binary system when checking if the lock is held causing subsequent evolution to proceed as if a fraction of above 1 was required. To properly put this issue to bed we must confirm that the evolution past the attempt to lock has the correct sign.

**Comment by kpenev** [comment]
The reason the above lock fraction was exactly zero was because the lock was for a term which did not contribute to the dissipation (m=1, m'=2) when the inclination is zero.

Verified that the evolution past the lock is correct.
